version: '3.7'
services:
  mysql-master1:
    image: uoles/mysql
    container_name: mysql-1
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "6611:3306"
    cap_add:
      - all
    volumes:
      - /home/uoles/project/mysql_db_haproxy_1:/var/lib/mysql
      - /home/uoles/project/mysql_db_haproxy_1_conf:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:8b03005ef88c426498523bbe0757d101
    networks:
      default:
        aliases:
          - mysql

  mysql-master2:
    image: uoles/mysql
    container_name: mysql-2
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "6612:3306"
    cap_add: 
      - all
    volumes:
      - /home/uoles/project/mysql_db_haproxy_2:/var/lib/mysql
      - /home/uoles/project/mysql_db_haproxy_2_conf:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:8b03005ef88c426498523bbe0757d101
    networks:
      default:
        aliases:
          - mysql

  haproxy:
    image: haproxytech/haproxy-ubuntu:latest
    container_name: haproxy
    restart: unless-stopped
    ports:
      - "2999:2999"
      - "3306:3306"
    cap_add:
      - all
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      default:
        aliases:
          - mysql
